env:
  node: true
  
extends:
  - airbnb-base

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: 0
  import/extentions: 
    - error
    - ignorePackages
    - js: always
